### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by kjarosh**
* Scrape more documentation
* Fix issues related to query params and filtering
* Fix broken links due to a wrong path used

In order to work, this mirror needs to have its own domain.

### CODE REVIEW

**Comment by torokati44** [comment]
> In order to work, this mirror needs to have its own domain.

Do we want to set up a new github.io site for this, or can this be merged before that?

**Comment by kjarosh** [comment]
The current path suggests we already have a separate domain for it, I'm just not sure :thinking:

**Comment by torokati44** [comment]
Let's see! 🤷‍♂️

**Comment by torokati44** [comment]
But, uhm, what are supposed to see, and where? 🤔

**Comment by kjarosh** [comment]
https://docs.ruffle.rs/ that's a simple index of all content there is. We should probably update readme too, TBH I thought I did it in this PR

**Comment by torokati44** [comment]
Oh, yay, nice! Did it work?

**Comment by kjarosh** [comment]
It seems to be working, yes.

**Comment by torokati44** [comment]
Woohoo, thank you in that case! 😊

**Pull request merged**
